In [2]:
# numpy= numpy is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. With numpy, you can perform a wide range of operations such as element-wise calculations, linear algebra, statistical analysis, and more. It is widely used in scientific computing, data analysis, and machine learning applications.

%pip install numpy 



Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np
# Create a 1D array
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1);
print(type(arr1))
print(arr1.shape)
arr2= arr1.reshape(2,5);
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.ones((3,4))
np.zeros((4,4))
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# numpy vectorized operations allow you to perform element-wise operations on arrays without the need for explicit loops. This can lead to more efficient and concise code. For example, if you have two arrays of the same shape, you can add them together directly:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# element wise addition
print("addition:", arr1+arr2)
print("subtraction:", arr1-arr2)
print("multiplication:", arr1*arr2)
print("division:", arr1/arr2)


addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [15]:
# some universal functions in numpy are:
# 1. np.sin() - computes the sine of each element in the array. 
# 2. np.cos() - computes the cosine of each element in the array.
# 3. np.exp() - computes the exponential of each element in the array.
# 4. np.log() - computes the natural logarithm of each element in the array.
# 5. np.sqrt() - computes the square root of each element in the array.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [27]:
# array slicing in numpy allows you to extract a portion of an array based on specified indices. You can use the following syntax for slicing:
# array[start:stop:step]

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array:\n",arr)
print("sliced array:\n",arr[0:2,1:3])
print(arr[0][0])
print("sliced array:\n",arr[1:,1:3])

array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sliced array:
 [[2 3]
 [5 6]]
1
sliced array:
 [[5 6]
 [8 9]]


In [29]:
# stastical concepts -- normalization
# to have a mean of 0 and a standard deviation of 1, you can use the following formula:
# normalized_value = (value - mean) / standard_deviation    
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
print("Mean:", mean)
std_dev = np.std(data)
print("Standard Deviation:", std_dev)
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# mean,median,mode,standard deviation,variance,percentiles
data = np.array([1, 2, 3, 4, 5, 5, 5, 6, 7, 8, 9])
mean = np.mean(data)
print("Mean:", mean)
median = np.median(data)
print("Median:", median)
from scipy import stats
mode = stats.mode(data) 
print("Mode:", mode.mode[0])
std_dev = np.std(data)
print("Standard Deviation:", std_dev)
variance = np.var(data)
print("Variance:", variance)
percentiles = np.percentile(data, [25, 50, 75])
print("Percentiles (25th, 50th, 75th):", percentiles)


In [34]:
# logical operations= logical operations in numpy allow you to perform element-wise comparisons and logical operations on arrays. Some common logical operations include:
data = np.array([1, 2, 3, 4, 5])
print("Greater than 3:", data > 3)
print(data[data > 3])
print("Less than or equal to 2:", data <= 2)
print("Logical AND (greater than 2 and less than 5):", (data > 2) & (data < 5))
print("Logical OR (less than 2 or greater than 4):", (data < 2) | (data > 4))

Greater than 3: [False False False  True  True]
[4 5]
Less than or equal to 2: [ True  True False False False]
Logical AND (greater than 2 and less than 5): [False False  True  True False]
Logical OR (less than 2 or greater than 4): [ True False False False  True]
